### ISSUE TITLE
Hardware newbie

### ISSUE THREAD

**Issue by zzolo** [adammhaile/RPi-LPD8806#7]
Thanks for the awesome work on this library.

This is definitely out of the scope of this library, but I thought I would ask.  Feel free to close if you don't have time.

I am a software developer just getting into the hardware side of things.  I was able to get my LPD8806 strip up and running on my Arduino (with [these instrucitons](http://learn.adafruit.com/digital-led-strip/wiring)), but I am having a harder time figuring out how to physically hook it up to my Raspberry Pi.

Can you provide a bit more details on how you wire this up exactly and how a level shifter fits into things?

Many thanks.

**Comment by adammhaile** [comment]
For arduino, follow this tutorial:
http://learn.adafruit.com/digital-led-strip/wiring
The level shifter doesn't come in to play as long as you are using a 5V
arduino.
The Raspberry Pi uses 3.3v logic levels and since the LPD8806 strips only
have input and not output you don't HAVE to use a level shifter with them
and the RPi, but it's recommended and helps with longer runs (more voltage,
more distance).
But again, as long as you arent using a 3.3v arduino, you don't need it.

**Comment by zzolo** [comment]
Thanks for the quick response!

I just found this as well:
http://learn.adafruit.com/system/assets/assets/000/001/589/medium800/diagram.png
